#include<stdio.h>
#include<stdlib.h>
#include<algorithm>
#include<iostream>
#include<map>
#include<vector>
#include<set>
#include<queue>
#include<string.h>
#include<utility>
#include<cctype>
#include<cmath>
#include<cstdio>
#include<cstdlib>
#include<cassert>
#include<cstring>